#!/bin/bash

##
# rodar como root 
##

#parando a rede
echo "Stopping Network Manager"
if [ -f /etc/debian_version ]; then
	sudo service network-manager stop
elif [[ -f /etc/redhat-release ]] || [[ -f /etc/arch-release ]]; then
	sudo pkill NetworkManager
fi

# carregando o batman
echo "Loading batman-adv kernel module"
modprobe batman-adv

sleep 2


ip link set up dev eth0
ip link set mtu 1532 dev wlan0


#ifconfig wlan0 down
#ifconfig wlan0 mtu 1532
#iwconfig wlan0 enc off

# add the interface to the ad-hoc network - or create it.
echo "switching to ad-hoc mode - batman"
iwconfig wlan0 mode ad-hoc channel 6 essid batman
#echo wlan0 > /proc/net/batman-adv/interfaces

# add wlan 0 na rede batman --bat0

echo "adding wireless interface to batman"
batctl if add wlan0

echo "bringing up wireless ad-hoc interface"
ifconfig wlan0 up
ifconfig bat0 192.168.10.1  #aqui to setando  o ip da placa na mão...

#echo wlan0 > /proc/net/batman-adv/interfaces
echo "bringing up bat0 interface"
ifconfig bat0 192.168.10.1 up


# look for neighbour nodes
#batctl -v 
#batctl o

echo "pronto."
